// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABorQf9M14UF4sa1_9czVnvctDU4Q2tTg',
    appId: '1:165581738317:web:133138873db5b62abea704',
    messagingSenderId: '165581738317',
    projectId: 'sltproject-17741',
    authDomain: 'sltproject-17741.firebaseapp.com',
    storageBucket: 'sltproject-17741.firebasestorage.app',
    measurementId: 'G-ZW0FF84NP0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABorQf9M14UF4sa1_9czVnvctDU4Q2tTg',
    appId: '1:165581738317:web:459b24a7cd32491dbea704',
    messagingSenderId: '165581738317',
    projectId: 'sltproject-17741',
    authDomain: 'sltproject-17741.firebaseapp.com',
    storageBucket: 'sltproject-17741.firebasestorage.app',
    measurementId: 'G-TBD37Y17YM',
  );
}
